### ISSUE TITLE
Package is shown as enabled in atom, but files are not autosaving when they lose focus

### ISSUE THREAD

**Issue by elwayman02** [atom/autosave#28]
I have a pretty basic project, just making minor changes to package.json/bower.json and a few js files, but none of the changes are saving without my explicit save attempt.

I'm used to Webstorm, where files just save as I make changes, even without losing focus....but at least having basic autosave functionality here would be nice.

Atom v0.141.0 on Windows 7 Pro

**Comment by lee-dohm** [comment]
The version of Atom you're running is pretty old. Atom is up to v0.179.0. Try updating to the latest version and let us know if this is still an issue.

You may need to refer to these instructions to remove the old Chocolatey installer version and install the new Squirrel-based installer version:

http://blog.atom.io/2014/12/10/a-windows-installer-and-updater.html

**Comment by seadour** [comment]
I'm having the same problem. Atom v1.2.0 on Mac OS X Yosemite.

**Comment by kmejka** [comment]
I'm having the same problem, Atom version 1.15.0, OSX Sierra. Any help?

**Comment by rsese** [comment]
> I'm having the same problem, Atom version 1.15.0, OSX Sierra. Any help?

@kmejka - this issue is pretty stale, can you open a new issue and fill out the issue template?

**Comment by kmejka** [comment]
@rsese I checked again and it seems though the package was enabled, it was disabled in the in the package specific 'Settings' view. This is pretty misleading to me, but marking the checkbox there fixed the problem. Why doesn't the autosave feature work automatically when I enable the plugin? Wouldn't it be a better decision to make the plugin work automatically after enabling it, without having to mark yet another checkbox?

Anyway - this issue is solved for me. Thanks!

**Comment by 50Wliu** [comment]
It's because all core packages are enabled by default, but not all users would necessarily want the autosave feature.

**Comment by kmejka** [comment]
I think you can close this issue.
