### ISSUE TITLE
Enabled by default?

### ISSUE THREAD

**Issue by asantos3** [atom/autosave#34]
Is there any specific reason for being "disabled by default"?

Also, can the pending PR's #22 and #31 be merged or what?

**Comment by thomasjo** [comment]
It's a feature that basically no text editor has enabled by default, and neither should it. Since it's highly uncommon default functionality, having it enabled by default would be surprising to most users.

Hence #22 will not be merged in it's current state — the enabled by default would need to be reverted. Also the way it's currently implementing the "save on destroy" is not ideal. It should be listening for Atom events, as opposed to `window.onbeforeunload`.

#31 would be better implemented using an enum option IMHO.
