### ISSUE TITLE
Auto Save not working,

### ISSUE THREAD

**Issue by grandmasterspoc** [atom/autosave#39]
I've had a million headaches trying to figure out why my code wasn't working or even changing.. all the while it's because my changes weren't getting saved. Please fix? :)

**Comment by 50Wliu** [comment]
Are you sure you have Autosave enabled?

**Comment by grandmasterspoc** [comment]
Positive

**Comment by balexand** [comment]
@grandmasterspoc You need to enable it in 2 different places for some reason (#14). Have you enabled it in both places?

![2015-06-11 at 11 33 am](https://cloud.githubusercontent.com/assets/181187/8113843/dd3aa1e0-102d-11e5-8879-7ac68372a400.png)

![2015-06-11 at 11 34 am](https://cloud.githubusercontent.com/assets/181187/8113877/30d92c4a-102e-11e5-8334-a6db40238bf6.png)

Never mind that in my screenshots I'm using my custom fork (`autosave-balexand`) since #35 hasn't been merged yet :sob:

**Comment by grandmasterspoc** [comment]
Geez I had no idea haha thank you so much! This saved me a million headaches :)
