### ISSUE TITLE
Description of Autosave package does not match actual defaults

### ISSUE THREAD

**Issue by afischli** [atom/autosave#60]
The Read Me text reads: "This package is disabled by default and can be enabled via the autosave.enabled config setting or from the Autosave section of the Settings view (cmd-,).". However, upon very first use of a virgin Atom v1.3.3 on a OS X 10.9.5 (Mavericks) system where I have never used Atom before the service was enabled.

**Comment by lee-dohm** [comment]
I cannot reproduce this using Atom v1.6.0-dev-62c1f6a on Mac OS X 10.11.2. Here's what I did:

1. Completely exited all instances of Atom
1. Executed the command `mv ~/.atom ~/.atom-backup`
1. Launched Atom again using `atom .`
1. Opened the Settings View using <kbd>Cmd+,</kbd>
1. Clicked the Packages tab
1. Searched for "autosave" and clicked the Settings button

Expected and Actual: Enabled was unchecked

<img width="527" alt="screen shot 2016-01-24 at 5 10 42 pm" src="https://cloud.githubusercontent.com/assets/1038121/12540407/6c0d59d4-c2bd-11e5-9bdf-695c78a763b8.png">

The contents of my new `~/.atom/config.cson` are:

```coffee
"*":
  core: {}
  editor:
    invisibles: {}
  "exception-reporting":
    userId: "12d55e58-9efe-df18-980d-20f697899bef"
  welcome:
    showOnStartup: false
```

Since `autosave.enabled` does not exist in the config settings above, it means the default is active. Also, the default is here in the code:

https://github.com/atom/autosave/blob/71c19a2c72396bd92d667642fbe72a6ab03c9e34/lib/autosave.coffee#L5-L8
