### ISSUE TITLE
Browser Refresh on Save: 208:211: syntax error: Expected end of line, etc. but found property. (-2741)

### ISSUE THREAD

**Issue by Beeckie68** [atom/autosave#65]
Since I updated the package in Atom last night I get this error message every time I press save:
Browser Refresh on Save: 208:211: syntax error: Expected end of line, etc. but found property. (-2741)

My config:
OS X 10.9.5
Atom 1.7.2
Safari 9.1

**Comment by 50Wliu** [comment]
Can you please paste the output of `apm list --installed` here?  Thanks.

**Comment by joanvila** [comment]
I have the same problem in chrome.

Here is my `apm list --installed` output:

Community Packages (19) /Users/myUser/.atom/packages
├── Remote-FTP@0.8.1
├── atom-beautify@0.29.7
├── browser-refresh-on-save@0.0.5
├── color-picker@2.1.1
├── emmet@2.4.3
├── git-time-machine@1.5.1
├── highlight-selected@0.11.2
├── hyperclick@0.0.36
├── hyperclick-php@0.2.1
├── js-hyperclick@1.4.2
├── line-count@0.5.0
├── linter@1.11.4
├── linter-jshint@2.1.0
├── linter-php@1.2.0
├── linter-phpcs@1.3.2
├── minimap@4.23.2
├── monokai@0.18.0
├── red-wavy-underline@0.3.0
└── todo-show@1.5.0

└── (empty)

**Comment by ProRepairz** [comment]
@Beeckie68  Hey, I was having the same problem, to me it seemed that there was something in the developers code that was causing my problem because my code was a sample text of  <body><h1>Hello world </h1></body> and I still received the same error Browser Refresh on Save: 208:211: syntax error: Expected end of line, etc. but found property. (-2741) 

Solution was:  you need to go to  Atom>Preferences>Packages>Browser-Refresh-on-Save>  check off the browsers you are not using I personally use Safari to Debug so leave that selected. I went over to refresh my code once again and it refreshed on save with out any issues.

**Comment by 50Wliu** [comment]
This seems like a problem with the browser-refresh-on-save package and not autosave, so please report this error over there instead.

**Comment by fmls1989** [comment]
@Beeckie68 how do you uncheck the browsers you are not using in atom? Im having the same issue here
