### ISSUE TITLE
Autosaves moved files

### ISSUE THREAD

**Issue by kevinsawicki** [atom/autosave#9]
Moving a file in the tree view causes an autosave.

Refs atom/tree-view#123

**Comment by MetaMemoryT** [comment]
:+1: super annoying

**Comment by bucaran** [comment]
What I do is close the file (if it is a file), `ctrl-0`, navigate to the directory / file, `m`, rename, and it does not create the duplicate.

Still, annoying indeed.

**Comment by bucaran** [comment]
@kevinsawicki Is there any way to disable "Do you really wan to delete this file?" dialog?

**Comment by rbu** [comment]
I like the addon a lot, but this is annoying. I rarely use rename in Atom, and use hg mv/git mv instead. Or I have a file open through an SSHFS mount. In all these cases, it just writes out files where they should not be. Even when closing them and the buffer is not even changed. It should simply check whether the file exists, then cancel the auto save and present the user with the usual "this file has unsaved changes" dialog.

**Comment by focusaurus** [comment]
Would love to see some talk of a fix in progress before the 1 year birthday of this issue. :cake: 

Getting the filesystem writes wrong in a text editor strikes me as a not-minor issue. This is a constant nuisance and to workaround it I have to use a command to close all my buffers, then switch to terminal to do my rename(s), then come back and re-open my buffers again. Very disruptive. When you get this dance wrong and end up with 2 versions of the file on disk, it seems likely you will edit the wrong one by mistake and end up losing or duplicating code plus getting confused when it comes time to do you git diff/add/commit work.

**Comment by thomasjo** [comment]
The package functionality is disabled by default, so a non-issue for most users. Until this gets resolved, return to the default state by un-ticking the *Enabled* checkbox.

I agree this should get some :eyes: soon, either in the form of a fix, or removal of the package.

**Comment by despairblue** [comment]
I'd rather live with this issue than see this package removed. Ever since
using scribes and later sublime text I never ever understood why autosave
on focus lost is not the default option for text editors, especially with
an undo history and having most files checked into some VCS anyhow. It's
something we do anyway, the chances of forgetting to save and rebuilding or
restarting are bigger than renaming a file and not seeing two files in the
navigator and thus end up editing the wrong one.

Fixing this issue and being able to open editors that disable this
selectively (useful for commit messages were you often alt tab while
writing them and they keep committing on save) are the only two things
getting in the way of enabling this by default ;) just kidding, but I'm
against removing it.

**Comment by balexand** [comment]
I've created a one-line fix for this in #35.

**Comment by paulcsmith** [comment]
I hope that gets merged in. This is the only problem I have with autosave. Other than that, this package is excellent!
