### ISSUE TITLE
It often fails to save and requires a restart of the atom editor

### ISSUE THREAD

**Issue by linjialiang** [atom/autosave#94]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
> When autosave is turned on, every now and then I can't save the content, which requires me to restart the atom editor

### Steps to Reproduce

**Expected behavior:** [What you expect to happen]
> I hope it doesn't fail to save

**Actual behavior:** [What actually happens]
> In fact, every once in a while something goes wrong

**Reproduces how often:** [What percentage of the time does it reproduce?]
> Especially when I write markdown documentation, the chances of it thriving are very high
### Versions

```bash
C:i>atom --version
Atom    : 1.34.0
Electron: 2.0.16
Chrome  : 61.0.3163.100
Node    : 8.9.3

C:>apm --version
apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.34.0
python 3.7.1
git 2.20.1.windows.1
visual studio
```

### Additional Information

```bash
Community Packages (40) C:\Users\linji\.atom\packages
├── atom-beautify@0.33.4
├── atom-ide-ui@0.13.0
├── atom-material-syntax@1.0.8
├── autocomplete-paths@2.12.2
├── autoprefixer@3.7.1
├── color-picker@2.3.0
├── docblockr@0.13.7
├── ex-mode@0.18.0
├── file-header@1.13.9
├── file-icons@2.1.30
├── git-time-machine@2.1.0
├── highlight-selected@0.14.0
├── ide-css@0.3.2
├── ide-html@0.5.0
├── ide-php@0.7.18
├── ide-typescript@0.8.0
├── language-ini@1.20.0
├── language-nginx@0.8.0
├── markdown-preview-enhanced@0.15.8
├── merge-conflicts@1.4.5
├── minimap@4.29.9
├── minimap-bookmarks@0.4.2
├── minimap-cursorline@0.2.0
├── minimap-find-and-replace@4.5.2
├── minimap-git-diff@4.3.1
├── minimap-highlight-selected@4.6.1
├── minimap-selection@4.5.0
├── minimap-split-diff@0.3.7
├── notepad-plus-plus-syntax@0.2.11
├── open-in-browser@0.5.2
├── pigments@0.40.2
├── platformio-ide-terminal@2.9.1
├── project-manager@3.3.6
├── regex-railroad-diagram@0.19.4
├── relative-numbers@0.9.0
├── remote-ftp@2.2.2
├── split-diff@1.6.0
├── sync-settings@0.8.6
├── tree-view-git-status@1.5.2
└── vim-mode-plus@1.36.0
```

**Comment by Aerijo** [comment]
@linjialiang You haven't confirmed this is in safe mode; does the issue occur in safe mode?

**Comment by linjialiang** [comment]
> In safe mode, no plugins, no plugins I haven't tested

**Comment by rsese** [comment]
> In safe mode, no plugins, no plugins I haven't tested

Just to clarify, you have not tested in safe mode yet?

**Comment by linjialiang** [comment]
> @rsese Safe mode will not have this problem

**Comment by rsese** [comment]
> @rsese Safe mode will not have this problem

Thanks for confirming :+1:

Since there's no problem in safe mode, then that likely means a community package or possibly something in your init script is causing the issue:

http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode

You can disable each community package one by one to try and pinpoint which is causing the problem.  Once you find the package causing the problem, we'll need the maintainer of the package that is causing the problem to help track that down. So we recommend that you file an issue on the package repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
